version: '3.5'
services:
  zookeeper:
    container_name: kafka-zk
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
        - kafka-network
  kafka:
    container_name: kafka-broker
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
    - '9092:9092'
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    networks:
        - kafka-network
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

networks:
  kafka-network:
    name: kafka-network